version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: blog_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog_frontend
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_BUCKET
      - S3_AVATARS_PREFIX
      - S3_CONTENT_IMAGES_PREFIX
      - S3_CONTENT_PDFS_PREFIX
      - PORT
    # Mount your source & node_modules, but isolate the Next.js build output
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
    command: npm run dev

volumes:
  node_modules:
  next_cache:
