const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { prisma } = require('./prisma');
const slugify = require('slugify');
const crypto = require('crypto');

const s3Client = new S3Client({
  region: process.env.AWS_REGION,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

const BUCKET = process.env.AWS_S3_BUCKET;
const IMAGES_PREFIX = process.env.S3_CONTENT_IMAGES_PREFIX || 'content-images';
const PDF_PREFIX = process.env.S3_CONTENT_PDFS_PREFIX || 'content-pdfs';

async function uploadFileToS3(fileData, prefix, filename) {
  const uniqueFilename = `${crypto.randomUUID()}_${filename}`;
  const key = `${prefix}/${uniqueFilename}`;

  let buffer;
  if (typeof fileData === 'string') {
    buffer = Buffer.from(fileData, 'base64');
  } else {
    buffer = fileData;
  }

  await s3Client.send(
    new PutObjectCommand({
      Bucket: BUCKET,
      Key: key,
      Body: buffer,
      ContentType: getMimeType(filename),
    })
  );

  const url = `https://${BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com/${encodeURI(key)}`;
  return { key, url };
}

async function generateUniqueSlug(title, model) {
  const baseSlug = slugify(title, { lower: true, strict: true });
  let uniqueSlug = baseSlug;
  let counter = 1;
  
  while (await model.findUnique({ where: { slug: uniqueSlug } })) {
    uniqueSlug = `${baseSlug}-${counter++}`;
  }
  
  return uniqueSlug;
}

async function createOrFindGenre(genreData) {
  const { id, name, description, isAutoGenerated, confidence, domain, createdBy } = genreData;
  
  // Check if genre exists by name (case-insensitive)
  const existingGenreByName = await prisma.genre.findFirst({
    where: {
      name: {
        equals: name,
        mode: 'insensitive'
      }
    }
  });
  
  if (existingGenreByName) {
    return { genre: existingGenreByName, wasCreated: false };
  }
  
  // Check if genre exists by ID (only if provided and different from auto-increment)
  const existingGenreById = id ? await prisma.genre.findUnique({
    where: { id }
  }) : null;
  
  // Create new genre (let Prisma auto-increment the ID)
  const newGenre = await prisma.genre.create({
    data: {
      name,
      description,
      isAutoGenerated: isAutoGenerated || false,
      confidence,
      domain,
      createdBy
    }
  });
  
  return { genre: newGenre, wasCreated: true };
}

async function createContentItem(contentData) {
  const { title, author, category, genreId, genre, summary, content, coverImage, pdfFile } = contentData;

  const modelMap = {
    Blog: prisma.blog,
    Book: prisma.book,
    Product: prisma.product,
  };
  
  const model = modelMap[category];
  if (!model) {
    throw new Error(`Invalid category: ${category}`);
  }

  let finalGenreId = genreId;
  let genreResult = null;
  
  // Handle genre auto-creation if genre object is provided
  if (genre && genre.isAutoGenerated) {
    const result = await createOrFindGenre(genre);
    finalGenreId = result.genre.id;
    genreResult = result;
  } else {
    // Use existing validation for traditional genreId-only uploads
    if (!await prisma.genre.findUnique({ where: { id: genreId } })) {
      throw new Error(`Genre ID ${genreId} does not exist`);
    }
  }

  let coverKey, coverUrl, pdfKey, pdfUrl;

  if (coverImage) {
    // Check if this is a placeholder image for programmatic uploads
    const isPlaceholder = coverImage.filename && 
                         coverImage.filename.includes('placeholder');
    const isMinimalPng = coverImage.data === "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChAFFeaR9cAAAAABJRU5ErkJggg==";
    
    if (isPlaceholder && isMinimalPng) {
      // Don't upload placeholder images to S3, just use filename
      coverKey = `placeholder/${coverImage.filename}`;
      coverUrl = `https://placeholder.digitaldossier.us/${coverImage.filename}`;
      console.log('📷 Using placeholder cover image without S3 upload');
    } else {
      const result = await uploadFileToS3(
        coverImage.data, 
        IMAGES_PREFIX, 
        coverImage.filename
      );
      coverKey = result.key;
      coverUrl = result.url;
    }
  }

  if (pdfFile) {
    const result = await uploadFileToS3(
      pdfFile.data, 
      PDF_PREFIX, 
      pdfFile.filename
    );
    pdfKey = result.key;
    pdfUrl = result.url;
  }

  const uniqueSlug = await generateUniqueSlug(title, model);
  const finalSummary = summary || content?.substring(0, 200) || '';

  const commonData = {
    title,
    slug: uniqueSlug,
    author: author || '',
    summary: finalSummary,
    content: content || '',
    cover_key: coverKey,
    pdf_key: pdfKey,
    genre: { connect: { id: finalGenreId } },
    updated_at: new Date(),
  };

  const newEntry = await model.create({ 
    data: commonData,
    include: { genre: true }
  });

  const result = {
    id: newEntry.id,
    title: newEntry.title,
    slug: newEntry.slug,
    author: newEntry.author,
    category,
    genreId: newEntry.genreId,
    genre: newEntry.genre?.name,
    summary: newEntry.summary,
    content: newEntry.content,
    coverKey: newEntry.coverKey,
    pdfKey: newEntry.pdfKey,
    coverUrl,
    pdfUrl,
    createdAt: newEntry.createdAt,
    updatedAt: newEntry.updatedAt,
  };
  
  // Include genre creation information if applicable
  if (genreResult) {
    result.genreInfo = {
      id: genreResult.genre.id,
      name: genreResult.genre.name,
      wasCreated: genreResult.wasCreated,
      createdAt: genreResult.genre.createdAt
    };
  }
  
  return result;
}

function validateContentData(data) {
  const errors = {};

  if (!data.title?.trim()) {
    errors.title = 'Title is required';
  }

  if (!data.category || !['Blog', 'Book', 'Product'].includes(data.category)) {
    errors.category = 'Category must be Blog, Book, or Product';
  }

  // Genre validation - either genreId or genre object required
  if (data.genre && data.genre.isAutoGenerated) {
    // Validate genre object for auto-creation
    if (!data.genre.id || !Number.isInteger(data.genre.id)) {
      errors.genreId = 'Valid genre ID is required in genre object';
    }
    if (!data.genre.name || typeof data.genre.name !== 'string' || data.genre.name.trim().length === 0) {
      errors.genreName = 'Genre name is required';
    }
    if (data.genre.name && data.genre.name.length > 50) {
      errors.genreName = 'Genre name must be 50 characters or less';
    }
    if (data.genre.confidence && (typeof data.genre.confidence !== 'number' || data.genre.confidence < 0 || data.genre.confidence > 1)) {
      errors.genreConfidence = 'Genre confidence must be a number between 0 and 1';
    }
  } else {
    // Traditional genreId validation
    if (!data.genreId || !Number.isInteger(data.genreId)) {
      errors.genreId = 'Valid genre ID is required';
    }
  }

  // Cover image validation - allow placeholders for programmatic uploads
  if (!data.coverImage || !data.coverImage.data) {
    errors.coverImage = 'Cover image is required';
  } else {
    // Check if this is a placeholder cover image for programmatic uploads
    const isPlaceholder = data.coverImage.filename && 
                         data.coverImage.filename.includes('placeholder');
    const isMinimalPng = data.coverImage.data === "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChAFFeaR9cAAAAABJRU5ErkJggg==";
    
    if (isPlaceholder && isMinimalPng) {
      console.log('📷 Accepting placeholder cover image for programmatic upload');
    }
  }

  if (data.coverImage && !['image/jpeg', 'image/png'].includes(data.coverImage.mimeType)) {
    errors.coverImage = 'Cover image must be JPEG or PNG';
  }

  if (data.pdfFile && data.pdfFile.mimeType !== 'application/pdf') {
    errors.pdfFile = 'PDF file must be application/pdf type';
  }

  return { isValid: Object.keys(errors).length === 0, errors };
}

function getMimeType(filename) {
  const ext = filename.toLowerCase().split('.').pop();
  const mimeTypes = {
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    png: 'image/png',
    pdf: 'application/pdf',
  };
  return mimeTypes[ext] || 'application/octet-stream';
}

module.exports = {
  uploadFileToS3,
  generateUniqueSlug,
  createOrFindGenre,
  createContentItem,
  validateContentData
};